# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75142cbf3a6ae121eaf17935503958d5e237a378e27bb1cf6d647875c16b8bce059b77bce882ab5a05f857757888f33f37216c3818784cc0f766ff6e0e0539f8

test:
  secret_key_base: 4f20aebceff08f860b79bcff463eba3a0ad1af112c043032f35f7f385276a546cc1d35ae55d9821566fcacf47b6ae00d9a91aa7ad2df172b58a322f7180bdf62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
